### ISSUE TITLE
Always thrown Error prompt requesting a New Issue to be reported here!

### ISSUE THREAD

**Issue by jarusaurus** [ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar#47]
I am not sure if this is related to the existing Python hard dependancy. 
but always getting the prompt to post this here. 

**As it showed: (also attaching the log file)** 

2. copy below exception message
Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Streamlink\Python\pythonw.exe
Node Path: C:\Users\suraj\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.
[2023-02-22.txt](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/files/10803018/2023-02-22.txt)
0\node-v16.18.0-win-x64\node.exe
Date: 02/22/2023 16:40:14
Exception:
Google Calendar Exception: 
Websites: https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar
Author: Ilja van Ipenburg
Version: 1.2.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\main.py", line 9, in <module>
    from plugin.main import GoogleCalendar
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\plugin\main.py", line 6, in <module>
    from ctparse import ctparse
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\ctparse\__init__.py", line 10, in <module>
    from ctparse.ctparse import ctparse, ctparse_gen  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\ctparse\ctparse.py", line 15, in <module>
    import regex
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\main.py", line 9, in <module>
    from plugin.main import GoogleCalendar
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\plugin\main.py", line 6, in <module>
    from ctparse import ctparse
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\ctparse\__init__.py", line 10, in <module>
    from ctparse.ctparse import ctparse, ctparse_gen  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\ctparse\ctparse.py", line 15, in <module>
    import regex
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\suraj\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 316
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ivanipenburg** [comment]
Hi yes this is indeed related to #39, I have not found a way to fix this yet.
