### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by hidayattaufiqur** [ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar#51]
Please type any relevant information here

Hello! first of all, I'd like to express my thanks to you for creating this handy plugin for FlowLauncher. 
back to the issue. somehow the error below kept showing whenever I tried to add event using your plugin. it seemed to me at first as though the query couldn't be parsed correctly because only the Upcoming Events are showing despite me giving any correct queries (talking about the examples you gave). 

here's the screenshot: 
![image](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/assets/67844213/2ebb2634-5328-4cdd-b8f9-9c029f185e25)

now, I've tinkered around with your code and I think I have found the issue. 
![image](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/assets/67844213/29a7dc13-7815-419d-905c-c7739e3e3cf2)

on line 42, somehow if I commented the code, it managed to work correctly. 
![image](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/assets/67844213/8629cd3c-f691-4caa-b6f7-921da8c16e6c)

I'm not sure if anyone has faced the same issue or it's somehow only happening in my machine. but, you might want to check that out. 

additional information:
- Python Version: 3.10 
- FlowLauncher Version: 1.15.0

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\ACER SWIFT\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\ACER SWIFT\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\ACER SWIFT\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\plugin\main.py", line 42, in query
    self.display_current_events()
  File "C:\Users\ACER SWIFT\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.2\plugin\main.py", line 117, in display_current_events
    self.show_result(event['summary'], subtitle, score=10-i, glyph_id=date_glyph_id, method="open_webpage", params=[event['htmlLink']])
KeyError: 'summary'

```
</p>
</details>

**Comment by hidayattaufiqur** [comment]
I just noticed that the issue is happening when the number of upcoming events on that day is less than the constant NUM_UPCOMING_EVENTS.

**Comment by hidayattaufiqur** [comment]
> I just noticed that the issue is happening when the number of upcoming events on that day is less than the constant NUM_UPCOMING_EVENTS.

I mistook the the root of the issue. it wasn't because of what I stated earlier, it was because some of my events in Gcal don't have 'summary' key in them. I will create a PR right after this to fix this possible issue. I will also close the issue now.
