### ISSUE TITLE
google calendar error: version 1.2.3 

### ISSUE THREAD

**Issue by debug-cli** [ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar#63]
exception: 

Flow Launcher version: 1.16.2
OS Version: 23601.1000
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/12/2023 17:18:12
Exception:
Google Calendar Exception: 
Websites: https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar
Author: Ilja van Ipenburg
Version: 1.2.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\main.py", line 9, in <module>
    from plugin.main import GoogleCalendar
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\plugin\main.py", line 6, in <module>
    from ctparse import ctparse
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\__init__.py", line 10, in <module>
    from ctparse.ctparse import ctparse, ctparse_gen  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\ctparse.py", line 15, in <module>
    import regex
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\main.py", line 9, in <module>
    from plugin.main import GoogleCalendar
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\plugin\main.py", line 6, in <module>
    from ctparse import ctparse
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\__init__.py", line 10, in <module>
    from ctparse.ctparse import ctparse, ctparse_gen  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\ctparse.py", line 15, in <module>
    import regex
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

log file 12/12/2023

[2023-12-12.txt](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/files/13654733/2023-12-12.txt)

**Comment by debug-cli** [comment]
may be some missing packages like `regex` and `cparse`

**Comment by debug-cli** [comment]
> may be some missing packages like `regex` and `cparse`

i ran the `pip install` command on both packages (`cparse` had more than one) and it still failed.
