### ISSUE TITLE
failed to respond

### ISSUE THREAD

**Issue by gorokhofff** [ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar#64]
[2024-02-09.txt](https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar/files/14220546/2024-02-09.txt)
Flow Launcher version: 1.17.1
OS Version: 22621.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\arthu\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 02/09/2024 13:25:03
Exception:
Google Calendar Exception: 
Websites: https://github.com/ivanipenburg/Flow.Launcher.Plugin.GoogleCalendar
Author: Ilja van Ipenburg
Version: 1.2.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\main.py", line 9, in <module>
    from plugin.main import GoogleCalendar
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\plugin\main.py", line 6, in <module>
    from ctparse import ctparse
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\__init__.py", line 10, in <module>
    from ctparse.ctparse import ctparse, ctparse_gen  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\ctparse.py", line 15, in <module>
    import regex
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\main.py", line 9, in <module>
    from plugin.main import GoogleCalendar
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\plugin\main.py", line 6, in <module>
    from ctparse import ctparse
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\__init__.py", line 10, in <module>
    from ctparse.ctparse import ctparse, ctparse_gen  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\ctparse\ctparse.py", line 15, in <module>
    import regex
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\arthu\AppData\Roaming\FlowLauncher\Plugins\Google Calendar-1.2.3\lib\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ivanipenburg** [comment]
Hi, thanks for filing an issue. The project is currently broken and I don't have time to fix it. I've requested to have it removed from FlowLauncher so other people won't run into the same issue.
